name: Build and publish package

on:
  push:
    branches: [ "master" ]
    
jobs:
  build-lib:
    runs-on: 'windows-latest'

    defaults:
      run:
        working-directory: src/Digbyswift.Core/Digbyswift.Core

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Pack
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build --output _package -p:SymbolPackageFormat=snupkg

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: .package
          path: src\Digbyswift.Core\Digbyswift.Core\_package
          retention-days: 5

  upload-lib:
    runs-on: 'windows-latest'

    needs: build-lib

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .package

      - name: Publish package to nuget
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push *.nupkg --api-key "${env:NUGET_API_KEY}" --source https://api.nuget.org/v3/index.json
